= What are you looking for?
:page-layout: home
:!sectids:
:!toc:

++++
<div class="cards">
++++

++++
<div class="card">
	<h3 class="card-header cloud"><img src="/home/_images/cloud.svg"></img>
		 hazelcast
	</h3>
	<p class="card-summary">
		Use Hazelcast as a managed service.
	</p>
	<ul>
		<li class="get-started-home">
			<a href="https://docs.cloud.hazelcast.com/docs/getting-started">Get Started <img src="/home/_images/right-arrow.svg"></a>
		</li>
	</ul>
++++

++++
	<h3 class="card-header imdg"><img src="/home/_images/imdg.svg"></img>
		 hazelcast
	</h3>
	<p class="card-summary">
		Run a Hazelcast IMDG cluster.
	</p>
	<ul>
		<li><a href="https://guides.hazelcast.org/home/">Integration Guides</a></li>
		<li><a href="https://hazelcast.com/resources/hazelcast-deployment-operations-guide/">Operations Guide</a></li>
		<li class="get-started-home">
			<a href="https://jakescahill.github.io/docs-poc/hazelcast/latest/getting-started.html">Get Started <img src="/home/_images/right-arrow.svg"></a>
		</li>
	</ul>
	
++++

++++
	<h3 class="card-header jet"><img src="/home/_images/jet.svg">
		 hazelcast
	</h3>
	<p class="card-summary">
		Run stateful computations over data.
	</p>
	<ul>
		<li><a href="https://jet-start.sh/docs/tutorials/kafka">Tutorials</a></li>
		<li><a href="https://jet-start.sh/docs/operations/installation">Operations Guide</a></li>
		<li class="get-started-home">
			<a href="https://jet-start.sh/docs/get-started/intro">Get Started <img src="/home/_images/right-arrow.svg"></a>
		</li>
	</ul>
</div>
++++

++++
<div class="card">
	<h3 class="card-header">
		Management Center
	</h3>
	<p class="card-summary">
		Monitor your Hazelcast clusters.
	</p>
	<ul>
		<li class="get-started-home">
			<a href="https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html#deploying-and-starting">Get Started <img src="/home/_images/right-arrow.svg"></a>
		</li>
	</ul>
++++

++++
	<h3 class="card-header">Hazelcast Clients
	</h3>
	<p class="card-summary">
		Connect to your Hazelcast clusters.
	</p>
	<ul>
		<li><a href="https://hazelcast.org/imdg/clients-languages/java/">Java (Client or Embedded)</a></li>
		<li><a href="https://hazelcast.org/imdg/clients-languages/dotnet/">.Net</a></li>
		<li><a href="https://hazelcast.org/imdg/clients-languages/cplusplus/">C++</a></li>
		<li><a href="https://hazelcast.org/imdg/clients-languages/node-js/">Node.js</a></li>
		<li><a href="https://hazelcast.org/imdg/clients-languages/python/">Python</a></li>
		<li><a href="https://hazelcast.org/imdg/clients-languages/go/">Go</a></li>
		<li><a href="https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#rest-client">REST</a></li>
		<li><a href="https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#memcache-client">Memcache</a></li>
	</ul>
</div>
++++

++++
<div class="card">
	<h3 class="card-header">See Also
	</h3>
	<p class="card-summary">
		Other helpful documentation resources.
	</p>
	<ul>
		<li><a href="https://hazelcast.org/hub/">Integration Hub</a>Explore our connectors and plugins for integrating Hazelcast with various data systems, application frameworks, and cloud runtimes.</li>
		<li><a href="https://training.hazelcast.com/">Online Training</a>Learn Hazelcast by following self-paced online training courses.</li>
		<li><a href="https://hazelcast.com/resources/mastering-hazelcast/">Mastering Hazelcast eBook</a>Get in-depth knowledge of the important features of Hazelcast IMDG</li>
	</ul>
</div>
++++

++++
</div>
++++