= Title of your tutorial topic
:description: Enter a brief description of your tutorial here, for example: This tutorial will get you started with the Hazelcast Python client and show you how to manipulate a map.

== Overview

{description}

This template includes writing instructions and boilerplate text that you can customize, use as-is, or replace with your own text.

Include the learning objectives (these may be in the description) and some rough timings. Ideally, your tutorial should take less than 60 minutes to complete as lengthy tutorials can overwhelm users. Consider condensing or removing steps or reevaluating the scope of the tutorial. For example: 

This tutorial will take approximately 10-15 minutes to complete.

Optionally, you may also want to state the intended audience. 

== Prerequisites

Use this section to tell users about any prerequisites needed before they start the tutorial, such as:

- Expected prior knowledge
- Software or hardware to obtain
- Environments to set up and configure
- Access codes to obtain

For example:

Before you begin, make sure you have the following:

- Python 3.6 or above
- Hazelcast Cloud Account
- A text editor or IDE

== Title of your first step

Tips for writing steps:

- Don't number your step's main headings (for example, don't use 'Step 1 - Configure the thing')
- Avoid gerunds (-ing words such as 'Configuring')
- Remember to orient users when guiding them through each step. If they need to open a particular file or dialog to complete the task, provide that information first
- Avoid writing procedures that are more than seven primary steps long
- Aim for no more than four substeps in any primary step

== Title of your second step

Rinse and repeat the steps until you complete the tutorial.

== Summary

Use this section to summarize what the user learned in the tutorial. For example: 

In this tutorial, you learned how to get started with the Hazelcast Python Client, connect to an instance, and put data into a distributed map.

== Next steps

Use this section to include links to other tutorials, such as tutorials that allow users to learn about related features. You can also include links to relevant resources, like articles, blogs, or videos. For example:

For more information, such as how you can query a map with predicates and SQL, check out the Python Client repository and the Python API documentation.

If you have any questions, suggestions, or feedback, contact the Hazelcast Community Slack. To contribute to the client, take a look at the issue list.
