= Title of your tutorial
:description: One or two sentences briefly describing the tutorial.

{description}

TIP: A tutorial is a complete worked example in a sandbox environment. It is different from a procedure or "how-to", which provides instructions for doing something on a real system. Tutorials are for learning, procedures are for doing. For more guidance, see link:https://diataxis.fr/start-here/#the-four-kinds-of-documentation[Diataxis] and link:https://gitlab.com/tgdp/templates/-/blob/main/tutorial/guide_tutorial.md[The Good Docs Project].

== Overview

A paragraph or two describing the tutorial in more detail. For example:

Learn how to back up Hazelcast map data to cloud storage and restore a cluster from the backup.

== Before you begin

List anything needed before users start the tutorial, such as:

- Tools or software
- Account access
- Prior knowledge

If you can't complete the tutorial without having this thing set up first, or you'd need to break out of the main flow to do something that could have been done in advance, it should be here. Include links for setup instructions.

For example:

Before you begin, make sure you have the following:

- Python 3.6 or above.
- A running Hazelcast cluster.

== Step 1: Do a thing

This is your first step. It might have a paragraph underneath.

. Or a numbered list.
. If there's more than one sub-step.

Explain any examples and note any placeholders that will need to be replaced with real values.

Avoid gerunds (-ing words) in titles -- say "Configure X", not "Configuring X". E.g. "Create a Hazelcast instance", "Configure high availability", "Enable persistence".

Include all the details users need to succeed. E.g. if you need to run a command on a member, include a step to sign in to the member.

== Step 2: Do the next thing

Add steps until you complete the tutorial. 

Include a final "clean up" step to reset any changes where appropriate, e.g. if the tutorial deploys resources in the cloud.

== Summary

Summarize what the user learned in the tutorial. For example: 

In this tutorial, you learned how to set up a Hazelcast cluster and use Management Center to view detailed information about members.

== Learn more

Include links to related tutorials, documentation, or other resources, typically in a bulleted list.